# Control file for continuous integration testing at http://travis-ci.org/

# ignore release tags
branches:
  except:
    /^\d+\.\d+(\.\d+)?(-\S*)?$/  

language: c++


git:
  depth: 100 # want to make sure we can find a version tag


jobs:
  include:
    - name: "RALibretro Win32"
      os: windows
      env: VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\
      script:
      - echo $VSINSTALLDIR
      - echo "${VSINSTALLDIR}VC\Auxiliary\Build\vcvars32.bat"
      - call "${VSINSTALLDIR}VC\Auxiliary\Build\vcvars32.bat"
      - msbuild.exe -version
    
    - name: "RALibretro Win32 cross-compile (Linux)"
      os: linux
      compiler: i686-w64-mingw32-gcc
      script: make ARCH=x86

    - name: "RALibretro Win64 cross-compile (Linux)"
      os: linux
      compiler: x86_64-w64-mingw32
      script: make ARCH=x64

    - name: "RAHasher x86 Linux"
      os: linux
      script: make ARCH=x86 -f Makefile.RAHasher

    - name: "RAHasher x64 Linux"
      os: linux
      script: make ARCH=x64 -f Makefile.RAHasher
